baseURL = "https://yusei-wy.github.io/hackerblog/"
canonifyurls = true
hasCJKLanguage = true
DefaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
languageCode = "ja"
title = "Hacker Blog"
theme = "hugo-theme-hello-friend-ng"

[params]
 # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
