baseURL = "https://yusei-wy.github.io/hackerblog/"
title = "Hacker Blog"
author = "yusei-wy"
canonifyurls = true
paginate = 3
theme = "hugo-theme-hello-friend-ng"
hasCJKLanguage = true
publishDir = "docs"
DefaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
languageCode = "ja"

[params]
 # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts"
